// 测试32位重定位 (R_RISCV_32, R_RISCV_32_PCREL, R_RISCV_ADD32, R_RISCV_SUB32)

// 这些重定位通常在调试信息和异常处理帧中使用
extern void external_function(void);

struct debug_info {
    unsigned int offset;
    unsigned int size;
};

// Note: ADD32/SUB32 relocations are typically generated by debug info,
// not regular code. We just demonstrate 32-bit address usage here.
unsigned int get_func_offset(void) {
    // This might generate R_RISCV_32_PCREL in debug sections
    return (unsigned int)(unsigned long)external_function;
}

void external_function(void) {
    // Empty implementation
}
